### ISSUE TITLE
No hay icono de la pagina

### ISSUE THREAD

**Issue by ivanespitiac** [DavidSanchezRuiz/interSolutions#45]
falta icono de la pagina que debe verse en esta parte:
![image](https://cloud.githubusercontent.com/assets/26120138/26591536/99300224-4523-11e7-879d-28eea8538841.png)

**Comment by josesoftwareII** [comment]
Hay un icono en la barra de paginas web, de la aplicación buenosplanes
![image](https://user-images.githubusercontent.com/17624905/27312793-30104340-5530-11e7-9613-5e428495d072.png)
