### ISSUE TITLE
Rango de las puntuaciones

### ISSUE THREAD

**Issue by ivanespitiac** [DavidSanchezRuiz/interSolutions#50]
El rango de las puntuaciones se muestran en forma numérica, aunque al momento de puntuar se realiza conforme a tres `items` (aburrido, agradable, divertido). 

![image](https://cloud.githubusercontent.com/assets/26120138/26592232/cd8d7798-4525-11e7-8987-8ece9a13d75c.png)

**Comment by DavidSanchezRuiz** [comment]
Se cambiaron por 3 iconos.
